extends Node

#Padrões de Balanço de Tela
const SHAKE_PATTERN_IDLE_AMPLITUDE = 0.0625
const SHAKE_PATTERN_IDLE_FREQUENCY = 1

const SHAKE_PATTERN_TRAIN_AMPLITUDE = 0.25
const SHAKE_PATTERN_TRAIN_FREQUENCY = 20

const SHAKE_PATTERN_DAMAGE_AMPLITUDE = 2
const SHAKE_PATTERN_DAMAGE_FREQUENCY = 100

#Padrões de Posição para a Câmera
const DEFAULT_CAMERA_POSITION = Vector2(0, -20);

#Valores Z-Index (usados dentro e fora dos scripts)
const BACKGROUND_Z_INDEX = -2

const WAGON_INTERIOR_Z_INDEX = -1

const PLAYER_RESERVED_Z_INDEX_LAYER_0 = 0
const PLAYER_RESERVED_Z_INDEX_LAYER_1 = 1
const PLAYER_RESERVED_Z_INDEX_LAYER_2 = 2
const PLAYER_RESERVED_Z_INDEX_LAYER_3 = 3
const PLAYER_RESERVED_Z_INDEX_LAYER_4 = 4
const PLAYER_WEAPON_RESERVED_Z_INDEX = 5

const WAGON_Z_INDEX = 6